### ISSUE TITLE
调研Face Alignment算法

### ISSUE THREAD

**Issue by tinytangent** [thucstsast/TinyMoeFace_Android#3]
参考《Face alignment by explicit shape regression》和《Supervised descent method and its applications to face alignment》两篇论文（CSDN上有更易于理解的相关资料），调研Explicit shape regression和Supervised descent method两种算法，并尝试完成脸部关键点的标记。

**Comment by carboncoo** [comment]
这两篇分别是12和13年的，我感觉可以考虑参考《Face Alignment at 3000 FPS via Regressing Local Binary Features》，是ESR那个组14年的文章，速度更快效率更好。当然我还没考虑具体实现的难度问题，感觉都挺难的......

**Comment by tinytangent** [comment]
谢谢提醒，这篇文章因为发得较晚引用数相对少，之前没有注意到……实现感觉确实都不是很容易……
贴几个Github上实现的链接……
《Face Alignment at 3000 FPS via Regressing Local Binary Features》有一个MATLAB的实现：
https://github.com/jwyang/face-alignment
另外ESR有个C++的OpenCV实现：https://github.com/soundsilence/FaceAlignment
SDM的Matlab实现：https://github.com/tntrung/impSDM

**Comment by tinytangent** [comment]
@carboncoo 已经较好地完成了调研工作，下面是Presentation的链接，大家可以参考。
他讲解的是基于《Face Alignment at 3000 FPS via Regressing Local Binary Features》，关于其中算法的细节，大家可以再网上查阅相关资料。
https://github.com/thucstsast/TinyMoeFace/files/554772/Face.Alignment.-.cjt4w.pptx
